FROM python:3.12-slim
RUN pip install --no-cache-dir pymisp==2.4.196 ujson
COPY classifier.py /app/classifier.py
RUN useradd -u 1000 -r -s /sbin/nologin classifier \
    && mkdir -p /state \
    && chown classifier:classifier /state
USER classifier
WORKDIR /app
ENTRYPOINT ["python", "classifier.py"]
